name: ci
on:
  push:
  pull_request:
    types: [opened, reopened]
env:
  PRODUCTION_BRANCH: refs/heads/production
  STAGING_BRANCH: refs/heads/staging

jobs:
  build:
    name: Build, Test, Lint
    uses: ./.github/workflows/build.yml

  deploy-staging:
    name: Deploy to Staging
    needs: [build]
    if: github.ref_name == 'staging'
    uses: ./.github/workflows/deploy.yml
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID_STAGING }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN_STAGING }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-ecr-repo: ${{ secrets.ECR_REPO }}
      fly-org-name: ${{ secrets.ORG_NAME_STAGING }}
      fly-app-name: ${{ secrets.APP_NAME_STAGING }}
      fly-api-token: ${{ secrets.FLY_API_TOKEN }}
    with:
      image-tag: ghactions-${{ github.ref_name }}-${{ github.sha }}

  deploy-production:
    name: Deploy to Production
    needs: [build]
    if: github.ref_name == 'production'
    uses: ./.github/workflows/deploy.yml
    secrets:
      aws-account-id: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN_PROD }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-ecr-repo: ${{ secrets.ECR_REPO }}
      fly-org-name: ${{ secrets.ORG_NAME_PROD }}
      fly-app-name: ${{ secrets.APP_NAME_PROD }}
      fly-api-token: ${{ secrets.FLY_API_TOKEN }}
    with:
      image-tag: ghactions-${{ github.ref_name }}-${{ github.sha }}
